name: namecoin
description: Dart library to interact with namecoin key/value
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
