name: namecoin
description: Dart library to interact with namecoin key/value
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
    # needed for
    # sha256hash
    # OP_CODES
    coinlib:
      git:
        url: https://github.com/julian-CStack/coinlib.git
        ref: 0acacfd17eacf72135c693a7b862bd9b7cc56739
        path: coinlib


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
