name: namecoin
description: Dart library to interact with namecoin key/value
version: 0.3.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
    # needed for
    # sha256hash
    # OP_CODES
    coinlib:
      git:
        url: https://github.com/cypherstack/coinlib.git
        ref: 980c8936f5679d6fea95b45822050be37a8c9011
        path: coinlib
    # needed for 
    # HMAC-RIPEMD160
    # pointycastle is a dep of coinlib, it doesn't add a new dep
    pointycastle: ^3.7.3


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  # needed for
  # examples
  electrum_adapter:
    git:
      url: https://github.com/cypherstack/electrum_adapter
      ref: 0de864a35c71fce3a07e6a53b623619b32394b8d
  args: ^2.6.0
  crypto: 3.0.2
  bip39:
    git:
      url: https://github.com/cypherstack/stack-bip39.git
      ref: 0cd6d54e2860bea68fc50c801cb9db2a760192fb
