name: namecoin
description: Dart library to interact with namecoin key/value
version: 0.2.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
    # needed for
    # sha256hash
    # OP_CODES
    coinlib:
      git:
        url: https://github.com/cypherstack/coinlib.git
        ref: 980c8936f5679d6fea95b45822050be37a8c9011
        path: coinlib
    # needed for 
    # HMAC-RIPEMD160
    # pointycastle is a dep of coinlib, it doesn't add a new dep
    pointycastle: ^3.7.3


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
